swagger: "2.0"
info:
  version: 1.0.0
  title: Note API

schemes:
  - http
basePath:
  $ref: 'commons.yaml#/basePath'

securityDefinitions:
  $ref: 'commons.yaml#/securityDefinitions'

consumes:
  $ref: 'commons.yaml#/consumes'
produces:
  $ref: 'commons.yaml#/produces'


paths:
  /notes:
    get:
      summary: Gets notes
      operationId: getNotes
      description: Return list of notes
      parameters:
        - name: username
          in: query
          type: string
        - name: householdId
          in: query
          type: string
        - name: sortingDirection
          in: query
          type: string
          enum:
            - ASC
            - DESC
        - name: sortedField
          in: query
          type: string
        - $ref: 'commons.yaml#/parameters/firstResult'
        - $ref: 'commons.yaml#/parameters/maxResult'
      responses:
        200:
          description: List of notes
          schema:
            $ref: '#/definitions/NotesPaging'
        500:
          $ref: 'commons.yaml#/responses/Standard500ErrorResponse'

    post:
      summary: Creates a note or patches if it already exists
      operationId: saveNote
      parameters:
        - name: note
          in: body
          description: Note to save
          schema:
            $ref: '#/definitions/Note'
      responses:
        201:
          description: Note succesfully saved.
          schema:
            type: string
        400:
          description: Note couldn't have been saved.
        500:
          $ref: 'commons.yaml#/responses/Standard500ErrorResponse'
  /notes/{id}:
    delete:
      summary: Deletes a note
      operationId: deleteNote
      parameters:
        - name: id
          in: path
          description: Id of note to delete
          type: string
          required: true
      responses:
        204:
          description: Note succesfully deleted.
        400:
          description: Note couldn't have been deleted.
        500:
          $ref: 'commons.yaml#/responses/Standard500ErrorResponse'

definitions:
  Note:
    required:
      - message
    properties:
      id:
        description: Note Id providing uniqueness in database
        type: string
        readOnly: true
      title:
        description: Note tile
        type: string
        default: ""
      message:
        description: Note message
        type: string
        default: ""
      recipent:
        description: Username of a person that the message is written to, null means that it is to everyone
        type: string
      creator:
        description: Username of a person that created the note
        type: string
      householdId:
        description: Household id that the note is written to
        type: string
        default: "testHousehold"
      expirationDate:
        description: Expiration date of a note
        type: string
        format: date
      visibleToEveryone:
        description: Describes if note can be seen by anyone in household
        type: boolean
        default: true

  NotesPaging:
    properties:
      array:
        type: array
        items:
          $ref: '#/definitions/Note'
      maxItems:
        type: integer

